  const stcloptions =[{
    value:'2017',
    label:'2017级',
    children:[{
      value:'信息',
      label:'信息系',
      children:[{
        value:'计算机1',
        label:'计算机1班',
      },{
        value:'计算机2',
        label:'计算机2班',
      },{
        value:'信管1',
        label:'信管1班',
      },{
        value:'信管2',
        label:'信管2班',
      },{
        value:'电子1',
        label:'电子1班',              
      },{
        value:'电子2',
        label:'电子2班',              
      }]
    },{
      value:'管理',
      label:'管理系',
      children:[{
        value:'财管1',
        label:'财务管理1班',
      },{
        value:'财管2',
        label:'财务管理2班',
      },{
        value:'财管3',
        label:'财务管理2班',
      },{
        value:'审计1',
        label:'审计1班',
      },{
        value:'审计2',
        label:'审计2班',              
      },{
        value:'人力1',
        label:'人力资源管理2班',              
      }]            
    },{
      value:'会计',
      label:'会计系',
      children:[{
        value:'会计1',
        label:'会计1班',
      },{
        value:'会计2',
        label:'会计2班',
      },{
        value:'会计3',
        label:'会计3班',
      },{
        value:'会计4',
        label:'会计4班',
      },{
        value:'会计5',
        label:'会计5班',              
      },{
        value:'会计6',
        label:'会计6班',              
      }]            
    }]
  },{
    value:'2018',
    label:'2018级',
    children:[{
      value:'信息',
      label:'信息系',
      children:[{
        value:'计算机1',
        label:'计算机1班',
      },{
        value:'计算机2',
        label:'计算机2班',
      },{
        value:'信管1',
        label:'信管1班',
      },{
        value:'信管2',
        label:'信管2班',
      },{
        value:'电子1',
        label:'电子1班',              
      },{
        value:'电子2',
        label:'电子2班',              
      }]
    },{
      value:'管理',
      label:'管理系',
      children:[{
        value:'财管1',
        label:'财务管理1班',
      },{
        value:'财管2',
        label:'财务管理2班',
      },{
        value:'财管3',
        label:'财务管理2班',
      },{
        value:'审计1',
        label:'审计1班',
      },{
        value:'审计2',
        label:'审计2班',              
      },{
        value:'人力1',
        label:'人力资源管理2班',              
      }]            
    },{
      value:'会计',
      label:'会计系',
      children:[{
        value:'会计1',
        label:'会计1班',
      },{
        value:'会计2',
        label:'会计2班',
      },{
        value:'会计3',
        label:'会计3班',
      },{
        value:'会计4',
        label:'会计4班',
      },{
        value:'会计5',
        label:'会计5班',              
      },{
        value:'会计6',
        label:'会计6班',              
      }]            
    }]
  },{
    value:'2019',
    label:'2019级',
    children:[{
      value:'信息',
      label:'信息系',
      children:[{
        value:'计算机1',
        label:'计算机1班',
      },{
        value:'计算机2',
        label:'计算机2班',
      },{
        value:'信管1',
        label:'信管1班',
      },{
        value:'信管2',
        label:'信管2班',
      },{
        value:'电子1',
        label:'电子1班',              
      },{
        value:'电子2',
        label:'电子2班',              
      }]
    },{
      value:'管理',
      label:'管理系',
      children:[{
        value:'财管1',
        label:'财务管理1班',
      },{
        value:'财管2',
        label:'财务管理2班',
      },{
        value:'财管3',
        label:'财务管理2班',
      },{
        value:'审计1',
        label:'审计1班',
      },{
        value:'审计2',
        label:'审计2班',              
      },{
        value:'人力1',
        label:'人力资源管理2班',              
      }]            
    },{
      value:'会计',
      label:'会计系',
      children:[{
        value:'会计1',
        label:'会计1班',
      },{
        value:'会计2',
        label:'会计2班',
      },{
        value:'会计3',
        label:'会计3班',
      },{
        value:'会计4',
        label:'会计4班',
      },{
        value:'会计5',
        label:'会计5班',              
      },{
        value:'会计6',
        label:'会计6班',              
      }]            
    }]
  },{
    value:'2020',
    label:'2020级',
    children:[{
      value:'信息',
      label:'信息系',
      children:[{
        value:'计算机1',
        label:'计算机1班',
      },{
        value:'计算机2',
        label:'计算机2班',
      },{
        value:'信管1',
        label:'信管1班',
      },{
        value:'信管2',
        label:'信管2班',
      },{
        value:'电子1',
        label:'电子1班',              
      },{
        value:'电子2',
        label:'电子2班',              
      }]
    },{
      value:'管理',
      label:'管理系',
      children:[{
        value:'财管1',
        label:'财务管理1班',
      },{
        value:'财管2',
        label:'财务管理2班',
      },{
        value:'财管3',
        label:'财务管理2班',
      },{
        value:'审计1',
        label:'审计1班',
      },{
        value:'审计2',
        label:'审计2班',              
      },{
        value:'人力1',
        label:'人力资源管理2班',              
      }]            
    },{
      value:'会计',
      label:'会计系',
      children:[{
        value:'会计1',
        label:'会计1班',
      },{
        value:'会计2',
        label:'会计2班',
      },{
        value:'会计3',
        label:'会计3班',
      },{
        value:'会计4',
        label:'会计4班',
      },{
        value:'会计5',
        label:'会计5班',              
      },{
        value:'会计6',
        label:'会计6班',              
      }]            
    }]
  }];
  export  default stcloptions;