       const  strmoptions = [{
          value:'1号楼',
          label:'1号楼',
          children:[{
            value:'1层',
            label:'1层',
            children:[{
              value:'101室',
              label:'101室',
            },{
              value:'102室',
              label:'102室',
            },{
              value:'103室',
              label:'103室',
            },{
              value:'104室',
              label:'104室',
            },{
              value:'105室',
              label:'105室',
            },{
              value:'106室',
              label:'106室',
            },{
              value:'107室',
              label:'107室',
            },{
              value:'108室',
              label:'108室',
            },{
              value:'109室',
              label:'109室',
            },{
              value:'110室',
              label:'110室',
            },{
              value:'111室',
              label:'111室',
            }]
          },{
            value:'2层',
            label:'2层',
            children:[{
              value:'201室',
              label:'201室',
            },{
              value:'202室',
              label:'202室',
            },{
              value:'203室',
              label:'203室',
            },{
              value:'204室',
              label:'204室',
            },{
              value:'205室',
              label:'205室',
            },{
              value:'206室',
              label:'206室',
            },{
              value:'207室',
              label:'207室',
            },{
              value:'208室',
              label:'208室',
            },{
              value:'209室',
              label:'209室',
            },{
              value:'210室',
              label:'210室',
            },{
              value:'211室',
              label:'211室',
            }]
          },{
            value:'3层',
            label:'3层',
            children:[{
              value:'301室',
              label:'301室',
            },{
              value:'302室',
              label:'302室',
            },{
              value:'303室',
              label:'303室',
            },{
              value:'304室',
              label:'304室',
            },{
              value:'305室',
              label:'305室',
            },{
              value:'306室',
              label:'306室',
            },{
              value:'307室',
              label:'307室',
            },{
              value:'308室',
              label:'308室',
            },{
              value:'309室',
              label:'309室',
            },{
              value:'310室',
              label:'310室',
            },{
              value:'311室',
              label:'311室',
            }]
          },{
            value:'4层',
            label:'4层',
            children:[{
              value:'401室',
              label:'401室',
            },{
              value:'402室',
              label:'402室',
            },{
              value:'403室',
              label:'403室',
            },{
              value:'404室',
              label:'404室',
            },{
              value:'405室',
              label:'405室',
            },{
              value:'406室',
              label:'406室',
            },{
              value:'407室',
              label:'407室',
            },{
              value:'408室',
              label:'408室',
            },{
              value:'409室',
              label:'409室',
            },{
              value:'410室',
              label:'410室',
            },{
              value:'411室',
              label:'411室',
            }]
          },{
            value:'5层',
            label:'5层',
            children:[{
              value:'501室',
              label:'501室',
            },{
              value:'502室',
              label:'502室',
            },{
              value:'503室',
              label:'503室',
            },{
              value:'504室',
              label:'504室',
            },{
              value:'505室',
              label:'505室',
            },{
              value:'506室',
              label:'506室',
            },{
              value:'507室',
              label:'507室',
            },{
              value:'508室',
              label:'508室',
            },{
              value:'509室',
              label:'509室',
            },{
              value:'510室',
              label:'510室',
            },{
              value:'511室',
              label:'511室',
            }]
          }]
        },{
          value:'2号楼',
          label:'2号楼',
          children:[{
            value:'1层',
            label:'1层',
            children:[{
              value:'101室',
              label:'101室',
            },{
              value:'102室',
              label:'102室',
            },{
              value:'103室',
              label:'103室',
            },{
              value:'104室',
              label:'104室',
            },{
              value:'105室',
              label:'105室',
            },{
              value:'106室',
              label:'106室',
            },{
              value:'107室',
              label:'107室',
            },{
              value:'108室',
              label:'108室',
            },{
              value:'109室',
              label:'109室',
            },{
              value:'110室',
              label:'110室',
            },{
              value:'111室',
              label:'111室',
            }]
          },{
            value:'2层',
            label:'2层',
            children:[{
              value:'201室',
              label:'201室',
            },{
              value:'202室',
              label:'202室',
            },{
              value:'203室',
              label:'203室',
            },{
              value:'204室',
              label:'204室',
            },{
              value:'205室',
              label:'205室',
            },{
              value:'206室',
              label:'206室',
            },{
              value:'207室',
              label:'207室',
            },{
              value:'208室',
              label:'208室',
            },{
              value:'209室',
              label:'209室',
            },{
              value:'210室',
              label:'210室',
            },{
              value:'211室',
              label:'211室',
            }]
          },{
            value:'3层',
            label:'3层',
            children:[{
              value:'301室',
              label:'301室',
            },{
              value:'302室',
              label:'302室',
            },{
              value:'303室',
              label:'303室',
            },{
              value:'304室',
              label:'304室',
            },{
              value:'305室',
              label:'305室',
            },{
              value:'306室',
              label:'306室',
            },{
              value:'307室',
              label:'307室',
            },{
              value:'308室',
              label:'308室',
            },{
              value:'309室',
              label:'309室',
            },{
              value:'310室',
              label:'310室',
            },{
              value:'311室',
              label:'311室',
            }]
          },{
            value:'4层',
            label:'4层',
            children:[{
              value:'401室',
              label:'401室',
            },{
              value:'402室',
              label:'402室',
            },{
              value:'403室',
              label:'403室',
            },{
              value:'404室',
              label:'404室',
            },{
              value:'405室',
              label:'405室',
            },{
              value:'406室',
              label:'406室',
            },{
              value:'407室',
              label:'407室',
            },{
              value:'408室',
              label:'408室',
            },{
              value:'409室',
              label:'409室',
            },{
              value:'410室',
              label:'410室',
            },{
              value:'411室',
              label:'411室',
            }]
          },{
            value:'5层',
            label:'5层',
            children:[{
              value:'501室',
              label:'501室',
            },{
              value:'502室',
              label:'502室',
            },{
              value:'503室',
              label:'503室',
            },{
              value:'504室',
              label:'504室',
            },{
              value:'505室',
              label:'505室',
            },{
              value:'506室',
              label:'506室',
            },{
              value:'507室',
              label:'507室',
            },{
              value:'508室',
              label:'508室',
            },{
              value:'509室',
              label:'509室',
            },{
              value:'510室',
              label:'510室',
            },{
              value:'511室',
              label:'511室',
            }]
          }]
        },{
          value:'3号楼',
          label:'3号楼',
          children:[{
            value:'1层',
            label:'1层',
            children:[{
              value:'101室',
              label:'101室',
            },{
              value:'102室',
              label:'102室',
            },{
              value:'103室',
              label:'103室',
            },{
              value:'104室',
              label:'104室',
            },{
              value:'105室',
              label:'105室',
            },{
              value:'106室',
              label:'106室',
            },{
              value:'107室',
              label:'107室',
            },{
              value:'108室',
              label:'108室',
            },{
              value:'109室',
              label:'109室',
            },{
              value:'110室',
              label:'110室',
            },{
              value:'111室',
              label:'111室',
            }]
          },{
            value:'2层',
            label:'2层',
            children:[{
              value:'201室',
              label:'201室',
            },{
              value:'202室',
              label:'202室',
            },{
              value:'203室',
              label:'203室',
            },{
              value:'204室',
              label:'204室',
            },{
              value:'205室',
              label:'205室',
            },{
              value:'206室',
              label:'206室',
            },{
              value:'207室',
              label:'207室',
            },{
              value:'208室',
              label:'208室',
            },{
              value:'209室',
              label:'209室',
            },{
              value:'210室',
              label:'210室',
            },{
              value:'211室',
              label:'211室',
            }]
          },{
            value:'3层',
            label:'3层',
            children:[{
              value:'301室',
              label:'301室',
            },{
              value:'302室',
              label:'302室',
            },{
              value:'303室',
              label:'303室',
            },{
              value:'304室',
              label:'304室',
            },{
              value:'305室',
              label:'305室',
            },{
              value:'306室',
              label:'306室',
            },{
              value:'307室',
              label:'307室',
            },{
              value:'308室',
              label:'308室',
            },{
              value:'309室',
              label:'309室',
            },{
              value:'310室',
              label:'310室',
            },{
              value:'311室',
              label:'311室',
            }]
          },{
            value:'4层',
            label:'4层',
            children:[{
              value:'401室',
              label:'401室',
            },{
              value:'402室',
              label:'402室',
            },{
              value:'403室',
              label:'403室',
            },{
              value:'404室',
              label:'404室',
            },{
              value:'405室',
              label:'405室',
            },{
              value:'406室',
              label:'406室',
            },{
              value:'407室',
              label:'407室',
            },{
              value:'408室',
              label:'408室',
            },{
              value:'409室',
              label:'409室',
            },{
              value:'410室',
              label:'410室',
            },{
              value:'411室',
              label:'411室',
            }]
          },{
            value:'5层',
            label:'5层',
            children:[{
              value:'501室',
              label:'501室',
            },{
              value:'502室',
              label:'502室',
            },{
              value:'503室',
              label:'503室',
            },{
              value:'504室',
              label:'504室',
            },{
              value:'505室',
              label:'505室',
            },{
              value:'506室',
              label:'506室',
            },{
              value:'507室',
              label:'507室',
            },{
              value:'508室',
              label:'508室',
            },{
              value:'509室',
              label:'509室',
            },{
              value:'510室',
              label:'510室',
            },{
              value:'511室',
              label:'511室',
            }]
          }]
        },{
          value:'4号楼',
          label:'4号楼',
          children:[{
            value:'1层',
            label:'1层',
            children:[{
              value:'101室',
              label:'101室',
            },{
              value:'102室',
              label:'102室',
            },{
              value:'103室',
              label:'103室',
            },{
              value:'104室',
              label:'104室',
            },{
              value:'105室',
              label:'105室',
            },{
              value:'106室',
              label:'106室',
            },{
              value:'107室',
              label:'107室',
            },{
              value:'108室',
              label:'108室',
            },{
              value:'109室',
              label:'109室',
            },{
              value:'110室',
              label:'110室',
            },{
              value:'111室',
              label:'111室',
            }]
          },{
            value:'2层',
            label:'2层',
            children:[{
              value:'201室',
              label:'201室',
            },{
              value:'202室',
              label:'202室',
            },{
              value:'203室',
              label:'203室',
            },{
              value:'204室',
              label:'204室',
            },{
              value:'205室',
              label:'205室',
            },{
              value:'206室',
              label:'206室',
            },{
              value:'207室',
              label:'207室',
            },{
              value:'208室',
              label:'208室',
            },{
              value:'209室',
              label:'209室',
            },{
              value:'210室',
              label:'210室',
            },{
              value:'211室',
              label:'211室',
            }]
          },{
            value:'3层',
            label:'3层',
            children:[{
              value:'301室',
              label:'301室',
            },{
              value:'302室',
              label:'302室',
            },{
              value:'303室',
              label:'303室',
            },{
              value:'304室',
              label:'304室',
            },{
              value:'305室',
              label:'305室',
            },{
              value:'306室',
              label:'306室',
            },{
              value:'307室',
              label:'307室',
            },{
              value:'308室',
              label:'308室',
            },{
              value:'309室',
              label:'309室',
            },{
              value:'310室',
              label:'310室',
            },{
              value:'311室',
              label:'311室',
            }]
          },{
            value:'4层',
            label:'4层',
            children:[{
              value:'401室',
              label:'401室',
            },{
              value:'402室',
              label:'402室',
            },{
              value:'403室',
              label:'403室',
            },{
              value:'404室',
              label:'404室',
            },{
              value:'405室',
              label:'405室',
            },{
              value:'406室',
              label:'406室',
            },{
              value:'407室',
              label:'407室',
            },{
              value:'408室',
              label:'408室',
            },{
              value:'409室',
              label:'409室',
            },{
              value:'410室',
              label:'410室',
            },{
              value:'411室',
              label:'411室',
            }]
          },{
            value:'5层',
            label:'5层',
            children:[{
              value:'501室',
              label:'501室',
            },{
              value:'502室',
              label:'502室',
            },{
              value:'503室',
              label:'503室',
            },{
              value:'504室',
              label:'504室',
            },{
              value:'505室',
              label:'505室',
            },{
              value:'506室',
              label:'506室',
            },{
              value:'507室',
              label:'507室',
            },{
              value:'508室',
              label:'508室',
            },{
              value:'509室',
              label:'509室',
            },{
              value:'510室',
              label:'510室',
            },{
              value:'511室',
              label:'511室',
            }]
          }]
        },{
          value:'5号楼',
          label:'5号楼',
          children:[{
            value:'1层',
            label:'1层',
            children:[{
              value:'101室',
              label:'101室',
            },{
              value:'102室',
              label:'102室',
            },{
              value:'103室',
              label:'103室',
            },{
              value:'104室',
              label:'104室',
            },{
              value:'105室',
              label:'105室',
            },{
              value:'106室',
              label:'106室',
            },{
              value:'107室',
              label:'107室',
            },{
              value:'108室',
              label:'108室',
            },{
              value:'109室',
              label:'109室',
            },{
              value:'110室',
              label:'110室',
            },{
              value:'111室',
              label:'111室',
            }]
          },{
            value:'2层',
            label:'2层',
            children:[{
              value:'201室',
              label:'201室',
            },{
              value:'202室',
              label:'202室',
            },{
              value:'203室',
              label:'203室',
            },{
              value:'204室',
              label:'204室',
            },{
              value:'205室',
              label:'205室',
            },{
              value:'206室',
              label:'206室',
            },{
              value:'207室',
              label:'207室',
            },{
              value:'208室',
              label:'208室',
            },{
              value:'209室',
              label:'209室',
            },{
              value:'210室',
              label:'210室',
            },{
              value:'211室',
              label:'211室',
            }]
          },{
            value:'3层',
            label:'3层',
            children:[{
              value:'301室',
              label:'301室',
            },{
              value:'302室',
              label:'302室',
            },{
              value:'303室',
              label:'303室',
            },{
              value:'304室',
              label:'304室',
            },{
              value:'305室',
              label:'305室',
            },{
              value:'306室',
              label:'306室',
            },{
              value:'307室',
              label:'307室',
            },{
              value:'308室',
              label:'308室',
            },{
              value:'309室',
              label:'309室',
            },{
              value:'310室',
              label:'310室',
            },{
              value:'311室',
              label:'311室',
            }]
          },{
            value:'4层',
            label:'4层',
            children:[{
              value:'401室',
              label:'401室',
            },{
              value:'402室',
              label:'402室',
            },{
              value:'403室',
              label:'403室',
            },{
              value:'404室',
              label:'404室',
            },{
              value:'405室',
              label:'405室',
            },{
              value:'406室',
              label:'406室',
            },{
              value:'407室',
              label:'407室',
            },{
              value:'408室',
              label:'408室',
            },{
              value:'409室',
              label:'409室',
            },{
              value:'410室',
              label:'410室',
            },{
              value:'411室',
              label:'411室',
            }]
          },{
            value:'5层',
            label:'5层',
            children:[{
              value:'501室',
              label:'501室',
            },{
              value:'502室',
              label:'502室',
            },{
              value:'503室',
              label:'503室',
            },{
              value:'504室',
              label:'504室',
            },{
              value:'505室',
              label:'505室',
            },{
              value:'506室',
              label:'506室',
            },{
              value:'507室',
              label:'507室',
            },{
              value:'508室',
              label:'508室',
            },{
              value:'509室',
              label:'509室',
            },{
              value:'510室',
              label:'510室',
            },{
              value:'511室',
              label:'511室',
            }]
          }]
        }];
        export default strmoptions;