<template>
  <div>
    <div class="login-container">
      <el-form :model="ruleForm" status-icon :rules="rules" ref="ruleForm" label-width="0px" class="login-form">
        <h3 class="title">系统登录<i class="" aria-hidden="true"></i></h3>
        <el-form-item prop="email">
          <el-input type="text" v-model="ruleForm.account" autocomplete="off" placeholder="用户名"></el-input>
        </el-form-item>
        <el-form-item  prop="pass">
          <el-input type="password" v-model="ruleForm.password" autocomplete="off" placeholder="密码"></el-input>
        </el-form-item>
          <el-button type="primary"  @click="submitForm()">登录</el-button>
          <el-button  class="middle" type="success" @click="dialogVisible = true">注册</el-button>
          <el-button class="right">忘记密码</el-button>
        </el-form-item>
      </el-form>
    </div>
    <div class="tanchuang">
      <el-dialog title="请填写注册信息" :visible="dialogVisible">
        <el-form :model="resetForm">
          <el-form-item label="账号" :label-width="formLabelWidth">      
            <el-input v-model="resetForm.account" autocomplete="off"></el-input>
          </el-form-item>
          <el-form-item label="密码" :label-width="formLabelWidth">      
            <el-input v-model="resetForm.password" autocomplete="off"></el-input>
          </el-form-item>
          <el-form-item label="再次输入密码" :label-width="formLabelWidth">      
            <el-input v-model="resetForm.conpassword" autocomplete="off"></el-input>
          </el-form-item>                        
          <el-form-item label="姓名" :label-width="formLabelWidth">
            <el-input v-model="resetForm.stname" autocomplete="off"></el-input>
          </el-form-item>
          <el-form-item label="班级" :label-width="formLabelWidth">
            <el-cascader
              v-model="resetForm.grade"
              separator="-"
              :options="stcloptions"
              :props="{expandTrigger:'hover'}"
            ></el-cascader>
          </el-form-item>
          <el-form-item label="宿舍号" :label-width="formLabelWidth">
            <el-cascader
              v-model="resetForm.sushehao"
              separator="-"
              :options="strmoptions"
              :props="{expandTrigger:'hover'}"
            ></el-cascader>
          </el-form-item>
          <el-form-item label="上传头像" :label-width="formLabelWidth">
            <el-upload
              class="avatar-uploader"
              :show-file-list="false"
              
            ></el-upload> 
          </el-form-item>          
        </el-form>
        <span slot="footer" class="dialog-footer">
          <el-button @click="dialogVisible =false">取消</el-button>
          <el-button type="primary" @click="dialogVisible =false;resetsub()">确认提交</el-button>
        </span>
      </el-dialog>       
    </div>    
  </div>
</template>
<script>
  import {global} from '../../global/global.js'
  export default {
    data() {
      return {
        formLabelWidth:'120px',
        loading:false,
        ruleForm: {
          account:'',
          password: '',
        },
        resetForm:{
          account:'',
          password:'',
          conpassword:'',
          stname:'',
          grade:[],
          sushehao:[],
        },
        dialogVisible:false,
        stcloptions:[{
          value:'2017',
          label:'2017级',
          children:[{
            value:'信息',
            label:'信息系',
            children:[{
              value:'计算机1',
              label:'计算机1班',
            },{
              value:'计算机2',
              label:'计算机2班',
            },{
              value:'信管1',
              label:'信管1班',
            },{
              value:'信管2',
              label:'信管2班',
            },{
              value:'电子1',
              label:'电子1班',              
            },{
              value:'电子2',
              label:'电子2班',              
            }]
          },{
            value:'管理',
            label:'管理系',
            children:[{
              value:'财管1',
              label:'财务管理1班',
            },{
              value:'财管2',
              label:'财务管理2班',
            },{
              value:'财管3',
              label:'财务管理2班',
            },{
              value:'审计1',
              label:'审计1班',
            },{
              value:'审计2',
              label:'审计2班',              
            },{
              value:'人力1',
              label:'人力资源管理2班',              
            }]            
          },{
            value:'会计',
            label:'会计系',
            children:[{
              value:'会计1',
              label:'会计1班',
            },{
              value:'会计2',
              label:'会计2班',
            },{
              value:'会计3',
              label:'会计3班',
            },{
              value:'会计4',
              label:'会计4班',
            },{
              value:'会计5',
              label:'会计5班',              
            },{
              value:'会计6',
              label:'会计6班',              
            }]            
          }]
        },{
          value:'2018',
          label:'2018级',
          children:[{
            value:'信息',
            label:'信息系',
            children:[{
              value:'计算机1',
              label:'计算机1班',
            },{
              value:'计算机2',
              label:'计算机2班',
            },{
              value:'信管1',
              label:'信管1班',
            },{
              value:'信管2',
              label:'信管2班',
            },{
              value:'电子1',
              label:'电子1班',              
            },{
              value:'电子2',
              label:'电子2班',              
            }]
          },{
            value:'管理',
            label:'管理系',
            children:[{
              value:'财管1',
              label:'财务管理1班',
            },{
              value:'财管2',
              label:'财务管理2班',
            },{
              value:'财管3',
              label:'财务管理2班',
            },{
              value:'审计1',
              label:'审计1班',
            },{
              value:'审计2',
              label:'审计2班',              
            },{
              value:'人力1',
              label:'人力资源管理2班',              
            }]            
          },{
            value:'会计',
            label:'会计系',
            children:[{
              value:'会计1',
              label:'会计1班',
            },{
              value:'会计2',
              label:'会计2班',
            },{
              value:'会计3',
              label:'会计3班',
            },{
              value:'会计4',
              label:'会计4班',
            },{
              value:'会计5',
              label:'会计5班',              
            },{
              value:'会计6',
              label:'会计6班',              
            }]            
          }]
        },{
          value:'2019',
          label:'2019级',
          children:[{
            value:'信息',
            label:'信息系',
            children:[{
              value:'计算机1',
              label:'计算机1班',
            },{
              value:'计算机2',
              label:'计算机2班',
            },{
              value:'信管1',
              label:'信管1班',
            },{
              value:'信管2',
              label:'信管2班',
            },{
              value:'电子1',
              label:'电子1班',              
            },{
              value:'电子2',
              label:'电子2班',              
            }]
          },{
            value:'管理',
            label:'管理系',
            children:[{
              value:'财管1',
              label:'财务管理1班',
            },{
              value:'财管2',
              label:'财务管理2班',
            },{
              value:'财管3',
              label:'财务管理2班',
            },{
              value:'审计1',
              label:'审计1班',
            },{
              value:'审计2',
              label:'审计2班',              
            },{
              value:'人力1',
              label:'人力资源管理2班',              
            }]            
          },{
            value:'会计',
            label:'会计系',
            children:[{
              value:'会计1',
              label:'会计1班',
            },{
              value:'会计2',
              label:'会计2班',
            },{
              value:'会计3',
              label:'会计3班',
            },{
              value:'会计4',
              label:'会计4班',
            },{
              value:'会计5',
              label:'会计5班',              
            },{
              value:'会计6',
              label:'会计6班',              
            }]            
          }]
        },{
          value:'2020',
          label:'2020级',
          children:[{
            value:'信息',
            label:'信息系',
            children:[{
              value:'计算机1',
              label:'计算机1班',
            },{
              value:'计算机2',
              label:'计算机2班',
            },{
              value:'信管1',
              label:'信管1班',
            },{
              value:'信管2',
              label:'信管2班',
            },{
              value:'电子1',
              label:'电子1班',              
            },{
              value:'电子2',
              label:'电子2班',              
            }]
          },{
            value:'管理',
            label:'管理系',
            children:[{
              value:'财管1',
              label:'财务管理1班',
            },{
              value:'财管2',
              label:'财务管理2班',
            },{
              value:'财管3',
              label:'财务管理2班',
            },{
              value:'审计1',
              label:'审计1班',
            },{
              value:'审计2',
              label:'审计2班',              
            },{
              value:'人力1',
              label:'人力资源管理2班',              
            }]            
          },{
            value:'会计',
            label:'会计系',
            children:[{
              value:'会计1',
              label:'会计1班',
            },{
              value:'会计2',
              label:'会计2班',
            },{
              value:'会计3',
              label:'会计3班',
            },{
              value:'会计4',
              label:'会计4班',
            },{
              value:'会计5',
              label:'会计5班',              
            },{
              value:'会计6',
              label:'会计6班',              
            }]            
          }]
        }],
        strmoptions:[{
          value:'1号楼',
          label:'1号楼',
          children:[{
            value:'1层',
            label:'1层',
            children:[{
              value:'101室',
              label:'101室',
            },{
              value:'102室',
              label:'102室',
            },{
              value:'103室',
              label:'103室',
            },{
              value:'104室',
              label:'104室',
            },{
              value:'105室',
              label:'105室',
            },{
              value:'106室',
              label:'106室',
            },{
              value:'107室',
              label:'107室',
            },{
              value:'108室',
              label:'108室',
            },{
              value:'109室',
              label:'109室',
            },{
              value:'110室',
              label:'110室',
            },{
              value:'111室',
              label:'111室',
            }]
          },{
            value:'2层',
            label:'2层',
            children:[{
              value:'201室',
              label:'201室',
            },{
              value:'202室',
              label:'202室',
            },{
              value:'203室',
              label:'203室',
            },{
              value:'204室',
              label:'204室',
            },{
              value:'205室',
              label:'205室',
            },{
              value:'206室',
              label:'206室',
            },{
              value:'207室',
              label:'207室',
            },{
              value:'208室',
              label:'208室',
            },{
              value:'209室',
              label:'209室',
            },{
              value:'210室',
              label:'210室',
            },{
              value:'211室',
              label:'211室',
            }]
          },{
            value:'3层',
            label:'3层',
            children:[{
              value:'301室',
              label:'301室',
            },{
              value:'302室',
              label:'302室',
            },{
              value:'303室',
              label:'303室',
            },{
              value:'304室',
              label:'304室',
            },{
              value:'305室',
              label:'305室',
            },{
              value:'306室',
              label:'306室',
            },{
              value:'307室',
              label:'307室',
            },{
              value:'308室',
              label:'308室',
            },{
              value:'309室',
              label:'309室',
            },{
              value:'310室',
              label:'310室',
            },{
              value:'311室',
              label:'311室',
            }]
          },{
            value:'4层',
            label:'4层',
            children:[{
              value:'401室',
              label:'401室',
            },{
              value:'402室',
              label:'402室',
            },{
              value:'403室',
              label:'403室',
            },{
              value:'404室',
              label:'404室',
            },{
              value:'405室',
              label:'405室',
            },{
              value:'406室',
              label:'406室',
            },{
              value:'407室',
              label:'407室',
            },{
              value:'408室',
              label:'408室',
            },{
              value:'409室',
              label:'409室',
            },{
              value:'410室',
              label:'410室',
            },{
              value:'411室',
              label:'411室',
            }]
          },{
            value:'5层',
            label:'5层',
            children:[{
              value:'501室',
              label:'501室',
            },{
              value:'502室',
              label:'502室',
            },{
              value:'503室',
              label:'503室',
            },{
              value:'504室',
              label:'504室',
            },{
              value:'505室',
              label:'505室',
            },{
              value:'506室',
              label:'506室',
            },{
              value:'507室',
              label:'507室',
            },{
              value:'508室',
              label:'508室',
            },{
              value:'509室',
              label:'509室',
            },{
              value:'510室',
              label:'510室',
            },{
              value:'511室',
              label:'511室',
            }]
          }]
        },{
          value:'2号楼',
          label:'2号楼',
          children:[{
            value:'1层',
            label:'1层',
            children:[{
              value:'101室',
              label:'101室',
            },{
              value:'102室',
              label:'102室',
            },{
              value:'103室',
              label:'103室',
            },{
              value:'104室',
              label:'104室',
            },{
              value:'105室',
              label:'105室',
            },{
              value:'106室',
              label:'106室',
            },{
              value:'107室',
              label:'107室',
            },{
              value:'108室',
              label:'108室',
            },{
              value:'109室',
              label:'109室',
            },{
              value:'110室',
              label:'110室',
            },{
              value:'111室',
              label:'111室',
            }]
          },{
            value:'2层',
            label:'2层',
            children:[{
              value:'201室',
              label:'201室',
            },{
              value:'202室',
              label:'202室',
            },{
              value:'203室',
              label:'203室',
            },{
              value:'204室',
              label:'204室',
            },{
              value:'205室',
              label:'205室',
            },{
              value:'206室',
              label:'206室',
            },{
              value:'207室',
              label:'207室',
            },{
              value:'208室',
              label:'208室',
            },{
              value:'209室',
              label:'209室',
            },{
              value:'210室',
              label:'210室',
            },{
              value:'211室',
              label:'211室',
            }]
          },{
            value:'3层',
            label:'3层',
            children:[{
              value:'301室',
              label:'301室',
            },{
              value:'302室',
              label:'302室',
            },{
              value:'303室',
              label:'303室',
            },{
              value:'304室',
              label:'304室',
            },{
              value:'305室',
              label:'305室',
            },{
              value:'306室',
              label:'306室',
            },{
              value:'307室',
              label:'307室',
            },{
              value:'308室',
              label:'308室',
            },{
              value:'309室',
              label:'309室',
            },{
              value:'310室',
              label:'310室',
            },{
              value:'311室',
              label:'311室',
            }]
          },{
            value:'4层',
            label:'4层',
            children:[{
              value:'401室',
              label:'401室',
            },{
              value:'402室',
              label:'402室',
            },{
              value:'403室',
              label:'403室',
            },{
              value:'404室',
              label:'404室',
            },{
              value:'405室',
              label:'405室',
            },{
              value:'406室',
              label:'406室',
            },{
              value:'407室',
              label:'407室',
            },{
              value:'408室',
              label:'408室',
            },{
              value:'409室',
              label:'409室',
            },{
              value:'410室',
              label:'410室',
            },{
              value:'411室',
              label:'411室',
            }]
          },{
            value:'5层',
            label:'5层',
            children:[{
              value:'501室',
              label:'501室',
            },{
              value:'502室',
              label:'502室',
            },{
              value:'503室',
              label:'503室',
            },{
              value:'504室',
              label:'504室',
            },{
              value:'505室',
              label:'505室',
            },{
              value:'506室',
              label:'506室',
            },{
              value:'507室',
              label:'507室',
            },{
              value:'508室',
              label:'508室',
            },{
              value:'509室',
              label:'509室',
            },{
              value:'510室',
              label:'510室',
            },{
              value:'511室',
              label:'511室',
            }]
          }]
        },{
          value:'3号楼',
          label:'3号楼',
          children:[{
            value:'1层',
            label:'1层',
            children:[{
              value:'101室',
              label:'101室',
            },{
              value:'102室',
              label:'102室',
            },{
              value:'103室',
              label:'103室',
            },{
              value:'104室',
              label:'104室',
            },{
              value:'105室',
              label:'105室',
            },{
              value:'106室',
              label:'106室',
            },{
              value:'107室',
              label:'107室',
            },{
              value:'108室',
              label:'108室',
            },{
              value:'109室',
              label:'109室',
            },{
              value:'110室',
              label:'110室',
            },{
              value:'111室',
              label:'111室',
            }]
          },{
            value:'2层',
            label:'2层',
            children:[{
              value:'201室',
              label:'201室',
            },{
              value:'202室',
              label:'202室',
            },{
              value:'203室',
              label:'203室',
            },{
              value:'204室',
              label:'204室',
            },{
              value:'205室',
              label:'205室',
            },{
              value:'206室',
              label:'206室',
            },{
              value:'207室',
              label:'207室',
            },{
              value:'208室',
              label:'208室',
            },{
              value:'209室',
              label:'209室',
            },{
              value:'210室',
              label:'210室',
            },{
              value:'211室',
              label:'211室',
            }]
          },{
            value:'3层',
            label:'3层',
            children:[{
              value:'301室',
              label:'301室',
            },{
              value:'302室',
              label:'302室',
            },{
              value:'303室',
              label:'303室',
            },{
              value:'304室',
              label:'304室',
            },{
              value:'305室',
              label:'305室',
            },{
              value:'306室',
              label:'306室',
            },{
              value:'307室',
              label:'307室',
            },{
              value:'308室',
              label:'308室',
            },{
              value:'309室',
              label:'309室',
            },{
              value:'310室',
              label:'310室',
            },{
              value:'311室',
              label:'311室',
            }]
          },{
            value:'4层',
            label:'4层',
            children:[{
              value:'401室',
              label:'401室',
            },{
              value:'402室',
              label:'402室',
            },{
              value:'403室',
              label:'403室',
            },{
              value:'404室',
              label:'404室',
            },{
              value:'405室',
              label:'405室',
            },{
              value:'406室',
              label:'406室',
            },{
              value:'407室',
              label:'407室',
            },{
              value:'408室',
              label:'408室',
            },{
              value:'409室',
              label:'409室',
            },{
              value:'410室',
              label:'410室',
            },{
              value:'411室',
              label:'411室',
            }]
          },{
            value:'5层',
            label:'5层',
            children:[{
              value:'501室',
              label:'501室',
            },{
              value:'502室',
              label:'502室',
            },{
              value:'503室',
              label:'503室',
            },{
              value:'504室',
              label:'504室',
            },{
              value:'505室',
              label:'505室',
            },{
              value:'506室',
              label:'506室',
            },{
              value:'507室',
              label:'507室',
            },{
              value:'508室',
              label:'508室',
            },{
              value:'509室',
              label:'509室',
            },{
              value:'510室',
              label:'510室',
            },{
              value:'511室',
              label:'511室',
            }]
          }]
        },{
          value:'4号楼',
          label:'4号楼',
          children:[{
            value:'1层',
            label:'1层',
            children:[{
              value:'101室',
              label:'101室',
            },{
              value:'102室',
              label:'102室',
            },{
              value:'103室',
              label:'103室',
            },{
              value:'104室',
              label:'104室',
            },{
              value:'105室',
              label:'105室',
            },{
              value:'106室',
              label:'106室',
            },{
              value:'107室',
              label:'107室',
            },{
              value:'108室',
              label:'108室',
            },{
              value:'109室',
              label:'109室',
            },{
              value:'110室',
              label:'110室',
            },{
              value:'111室',
              label:'111室',
            }]
          },{
            value:'2层',
            label:'2层',
            children:[{
              value:'201室',
              label:'201室',
            },{
              value:'202室',
              label:'202室',
            },{
              value:'203室',
              label:'203室',
            },{
              value:'204室',
              label:'204室',
            },{
              value:'205室',
              label:'205室',
            },{
              value:'206室',
              label:'206室',
            },{
              value:'207室',
              label:'207室',
            },{
              value:'208室',
              label:'208室',
            },{
              value:'209室',
              label:'209室',
            },{
              value:'210室',
              label:'210室',
            },{
              value:'211室',
              label:'211室',
            }]
          },{
            value:'3层',
            label:'3层',
            children:[{
              value:'301室',
              label:'301室',
            },{
              value:'302室',
              label:'302室',
            },{
              value:'303室',
              label:'303室',
            },{
              value:'304室',
              label:'304室',
            },{
              value:'305室',
              label:'305室',
            },{
              value:'306室',
              label:'306室',
            },{
              value:'307室',
              label:'307室',
            },{
              value:'308室',
              label:'308室',
            },{
              value:'309室',
              label:'309室',
            },{
              value:'310室',
              label:'310室',
            },{
              value:'311室',
              label:'311室',
            }]
          },{
            value:'4层',
            label:'4层',
            children:[{
              value:'401室',
              label:'401室',
            },{
              value:'402室',
              label:'402室',
            },{
              value:'403室',
              label:'403室',
            },{
              value:'404室',
              label:'404室',
            },{
              value:'405室',
              label:'405室',
            },{
              value:'406室',
              label:'406室',
            },{
              value:'407室',
              label:'407室',
            },{
              value:'408室',
              label:'408室',
            },{
              value:'409室',
              label:'409室',
            },{
              value:'410室',
              label:'410室',
            },{
              value:'411室',
              label:'411室',
            }]
          },{
            value:'5层',
            label:'5层',
            children:[{
              value:'501室',
              label:'501室',
            },{
              value:'502室',
              label:'502室',
            },{
              value:'503室',
              label:'503室',
            },{
              value:'504室',
              label:'504室',
            },{
              value:'505室',
              label:'505室',
            },{
              value:'506室',
              label:'506室',
            },{
              value:'507室',
              label:'507室',
            },{
              value:'508室',
              label:'508室',
            },{
              value:'509室',
              label:'509室',
            },{
              value:'510室',
              label:'510室',
            },{
              value:'511室',
              label:'511室',
            }]
          }]
        },{
          value:'5号楼',
          label:'5号楼',
          children:[{
            value:'1层',
            label:'1层',
            children:[{
              value:'101室',
              label:'101室',
            },{
              value:'102室',
              label:'102室',
            },{
              value:'103室',
              label:'103室',
            },{
              value:'104室',
              label:'104室',
            },{
              value:'105室',
              label:'105室',
            },{
              value:'106室',
              label:'106室',
            },{
              value:'107室',
              label:'107室',
            },{
              value:'108室',
              label:'108室',
            },{
              value:'109室',
              label:'109室',
            },{
              value:'110室',
              label:'110室',
            },{
              value:'111室',
              label:'111室',
            }]
          },{
            value:'2层',
            label:'2层',
            children:[{
              value:'201室',
              label:'201室',
            },{
              value:'202室',
              label:'202室',
            },{
              value:'203室',
              label:'203室',
            },{
              value:'204室',
              label:'204室',
            },{
              value:'205室',
              label:'205室',
            },{
              value:'206室',
              label:'206室',
            },{
              value:'207室',
              label:'207室',
            },{
              value:'208室',
              label:'208室',
            },{
              value:'209室',
              label:'209室',
            },{
              value:'210室',
              label:'210室',
            },{
              value:'211室',
              label:'211室',
            }]
          },{
            value:'3层',
            label:'3层',
            children:[{
              value:'301室',
              label:'301室',
            },{
              value:'302室',
              label:'302室',
            },{
              value:'303室',
              label:'303室',
            },{
              value:'304室',
              label:'304室',
            },{
              value:'305室',
              label:'305室',
            },{
              value:'306室',
              label:'306室',
            },{
              value:'307室',
              label:'307室',
            },{
              value:'308室',
              label:'308室',
            },{
              value:'309室',
              label:'309室',
            },{
              value:'310室',
              label:'310室',
            },{
              value:'311室',
              label:'311室',
            }]
          },{
            value:'4层',
            label:'4层',
            children:[{
              value:'401室',
              label:'401室',
            },{
              value:'402室',
              label:'402室',
            },{
              value:'403室',
              label:'403室',
            },{
              value:'404室',
              label:'404室',
            },{
              value:'405室',
              label:'405室',
            },{
              value:'406室',
              label:'406室',
            },{
              value:'407室',
              label:'407室',
            },{
              value:'408室',
              label:'408室',
            },{
              value:'409室',
              label:'409室',
            },{
              value:'410室',
              label:'410室',
            },{
              value:'411室',
              label:'411室',
            }]
          },{
            value:'5层',
            label:'5层',
            children:[{
              value:'501室',
              label:'501室',
            },{
              value:'502室',
              label:'502室',
            },{
              value:'503室',
              label:'503室',
            },{
              value:'504室',
              label:'504室',
            },{
              value:'505室',
              label:'505室',
            },{
              value:'506室',
              label:'506室',
            },{
              value:'507室',
              label:'507室',
            },{
              value:'508室',
              label:'508室',
            },{
              value:'509室',
              label:'509室',
            },{
              value:'510室',
              label:'510室',
            },{
              value:'511室',
              label:'511室',
            }]
          }]
        }]
      };
    },
    methods: {
      submitForm() {
        var vm = this;
        var par = JSON.parse(JSON.stringify(vm.ruleForm));
        vm.$store.dispatch('LoginByEmail',par).then((res)=>{
          console.log('登录成功即将跳转。。。。。。')
          vm.$router.push({path:'/'});
        })   
      },
      resetsub(){
        let vm = this;
        let par = JSON.parse(JSON.stringify(vm.resetForm));
        global.post('/api/login/reset',par,(res)=>{
          console.log(res)
        },(res)=>{
          console.log(res)
        })
      }
    }
  };
</script>
<style rel="stylesheet/scss" lang="scss">
    .login-container {
        position:relative;
        height: 100vh;
        /*background-color: #2d4a4b;*/
       
        background: url('../../assets/img/bg_sky.jpg') no-repeat;
        background-size: 100% 100%;
        
        input:-webkit-autofill {
            -webkit-box-shadow: 0 0 0px 1000px #294444 inset !important;
            -webkit-text-fill-color: #fff !important;
        }
        input {
            background: transparent;
            border: 0px;
            -webkit-appearance: none;
            border-radius: 0px;
            padding: 12px 5px 12px 15px;
            color: #eeeeee;
            height: 47px;
        }
        el-input {
            display: inline-block;
            height: 47px;
            width: 85%;
        }
        .title {
            font-size: 26px;
            font-weight: 400;
            color: #eeeeee;
            margin: 0px auto 40px auto;
            text-align: center;
            font-weight: bold;
        }
        .login-form {
            position: absolute;
            left: 0;
            right: 0;
            width: 400px;
            padding: 35px 35px 15px 35px;
            margin: 120px auto;
        }
        .el-form-item {
            border: 1px solid rgba(255, 255, 255, 0.1);
            background: rgba(0, 0, 0, 0.1);
            border-radius: 5px;
            color: #454545;
        }
        .middle{
          margin-left:80px !important;
        }
    }
    .tanchuang{
      .el-input{
        width:300px;
      }
    }
</style>